modLoader = "javafml"
loaderVersion = "[47,)"
issueTrackerURL = "https://github.com/HO-Artisan/FlameSweeping/issues"
license = "MIT"

[[mods]]
modId = "flame_sweeping"
version = "${version}"
displayName = "Flame Sweeping"
authors = "HO-Artisan"
description = '''
Sweeping with flame!
'''
logoFile = "banner.png"